# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Turing Commons
author: Dr Christopher Burr
copyright: This work is licensed under a Creative Commons Attribution 4.0 International License.
logo: "./images/logo.png"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/chrisdburr/turing-commons  # Online location of your book
  path_to_book: guidebooks  # Optional path to your book, relative to the repository root

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: <a href="https://www.netlify.com"><img src="https://www.netlify.com/img/global/badges/netlify-color-accent.svg" alt="Deploys by Netlify" /></a></br></br>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  comments:
    hypothesis: true

#settings
sphinx:
  config:
    language: en
    html_show_copyright: false
    bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_extra_path: ['assets']

#Bibliography
bibtex_bibfiles:
    - references.bib

#Launch services
launch_buttons:
  notebook_interface: "jupyterlab"  
  binderhub_url: "https://hub-binder.mybinder.ovh/user/chrisdburr-turing-commons-ntm7m74q/lab"  # The URL for your BinderHub (e.g., https://mybinder.org)

